title: Jeidsan Pereira
description: Um blog sobre tecnologia, cultura e sociedade.
keywords: tecnologia, cultura, sociedade, jeidsan, jeidsan pereira, blog
author: Jeidsan Pereira
email: contato@jeidsan.com.br

baseurl: "/blog"
url: "https://www.jeidsan.com.br"

social:  
  lattes: 5298030678650595
  linkedin: jeidsan
  facebook: jeidsan
  instagram: jeidsan
  github: jeidsan